// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddjjtumgquimsgqwkgvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkamp0dW1ncXVpbXNncXdrZ3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjA2MTAsImV4cCI6MjA3MDU5NjYxMH0.AzQgs6w8i2NI-oCOPC3-VnPqEoCFJ2MS-02rtuKEmUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});